Added Baritone integration
maxsupermanhd/meteor-villager-roller pull request #29
Opened 2023-08-19 06:11 UTC by The0nePlyer

Added baritone integration as well as a few optimizations.

2023-08-19 06:26 UTC, The0nePlyer commented
Fixed a typo

2023-08-19 09:11 UTC, maxsupermanhd commented
I really believe there is a better way of setting baritone goals, there is a place block goal that probably should be used

2023-08-19 09:37 UTC, maxsupermanhd requested changes

2023-08-19 09:37 UTC, maxsupermanhd commented on src/main/java/maxsuperman/addons/roller/modules/VillagerRoller.java
> +            }
It still can actually, better inform user about it properly.
Also what happened to indentation here?

2023-08-19 09:37 UTC, maxsupermanhd commented on src/main/java/maxsuperman/addons/roller/modules/VillagerRoller.java
> +                BaritoneAPI.getProvider().getPrimaryBaritone().getCommandManager().execute("sel clear");
`GoalPlace` from `baritone.process` should be used (through `ICustomGoalProcess`)

2025-02-16 07:30 UTC, maxsupermanhd commented
superseded by #44

2025-02-16 07:30 UTC, closed without merging